tap 'AlexanderWillner/tap'
tap 'alecthomas/tap'
tap 'fsouza/prettierd'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/core'
tap 'jesseduffield/lazydocker'
tap 'nexeck/homebrew-tmuxinator'
tap 'tinygo-org/tools'

brew 'ack' 
brew 'aspell'
brew 'awscli'
brew 'bash'
brew 'bat'
brew 'cask'
brew 'cmake'
brew 'coreutils'
brew 'ctop'
brew 'fish'
brew 'fnm'
brew 'fsouza/prettierd/prettierd'
brew 'fzf'
brew 'gh'
brew 'gifsicle'
brew 'git'
brew 'gnu-getopt'
brew 'gnu-sed'
brew 'gnupg', link: false
brew 'gnutls'
brew 'go'
brew 'gpg2'
brew 'gping'
brew 'htop'
brew 'httpie'
brew 'helix'
brew 'hugo'
brew 'imagemagick'
brew 'jpeg'
brew 'jq'
brew 'kind'
brew 'lazydocker'
brew 'lazygit'
brew 'luarocks'
brew 'lua-language-server'
brew 'marksman'
brew 'mas'
brew 'mercurial'
brew 'neovim'
brew 'pandoc'
brew 'perl'
brew 'pinentry'
brew 'pnpm'
brew 'prettyping'
brew 'python'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'rust'
brew 'rust-analyzer'
brew 'safe-rm'
brew 'shfmt'
brew 'siege'
brew 'starship'
brew 'stow'
brew 'stylua'
brew 'taplo'
brew 'terminal-notifier'
brew 'thefuck'
brew 'tidy-html5'
brew 'tinygo'
brew 'tldr'
brew 'tmux'
brew 'trash'
brew 'tree-sitter'
brew 'vim'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'zsh-completions'

# Fonts
cask 'font-anonymous-pro'
cask 'font-fira-code'
cask 'font-hack'
cask 'font-hack-nerd-font'
cask 'font-ibm-plex'
cask 'font-inconsolata'
cask 'font-jetbrains-mono-nerd-font'
cask 'font-montserrat'
cask 'font-open-sans'
cask 'font-oswald'
cask 'font-pt-mono'
cask 'font-roboto'
cask 'font-roboto-mono'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-work-sans'

# Applications
cask '1password'
cask '1password/tap/1password-cli'
cask 'alacritty'
cask 'appcleaner'
cask 'brave-browser'
cask 'cleanshot'
cask 'cryptomator'
cask 'devonthink'
cask 'docker'
cask 'figma'
cask 'firefox'
cask 'google-chrome'
cask 'grammarly-desktop'
cask 'imageoptim'
cask 'obsidian'
cask 'osxfuse'
cask 'postico'
cask 'signal'
cask 'transmission'
cask 'visual-studio-code'
cask 'webstorm'
cask 'zoom'

# Mac App Store 
mas '1Password for Safari', id: 568903335
mas 'AdGuard for Safari', id: 1440147259
mas 'Anybox', id: 1593408455
mas 'Lungo', id: 1263070803
mas 'Magnet', id: 441258766
mas 'Meeter', id: 1510445899
mas 'Pixelmator Pro', id: 1289583905
mas 'Slack', id: 803453959
mas 'Vimari', id: 1480933944
mas 'Vinegar', id: 1591303229
mas 'Xcode', id: 497799835
mas 'xScope', id: 889428659
