tap 'alecthomas/tap'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/core'
tap 'jesseduffield/lazydocker'
tap 'nexeck/homebrew-tmuxinator'
tap 'tinygo-org/tools'

brew 'ack'
brew 'aspell'
brew 'autoconf'
brew 'automake'
brew 'awscli'
brew 'bash'
brew 'bat'
brew 'boost'
brew 'cask'
brew 'cmake'
brew 'coreutils'
brew 'cscope'
brew 'ctop'
brew 'dep'
brew 'diff-so-fancy'
brew 'fish'
brew 'fnm'
brew 'fontforge'
brew 'freetype'
brew 'fzf'
brew 'gettext'
brew 'gh'
brew 'gifsicle'
brew 'git'
brew 'gnu-getopt'
brew 'gnupg', link: false
brew 'gnutls'
brew 'go'
brew 'gping'
brew 'graphviz'
brew 'htop'
brwe 'gpg2'
brew 'httpie'
brew 'hugo'
brew 'imagemagick'
brew 'jemalloc'
brew 'jpeg'
brew 'jq'
brew 'lazydocker'
brew 'lazygit'
brew 'luajit'
brew 'luarocks'
brew 'mas'
brew 'mercurial'
brew 'mono'
brew 'msgpack'
brew 'mysql'
brew 'ncurses'
brew 'neovim'
brew 'npth'
brew 'pandoc'
brew 'pass'
brew 'perl'
brew 'pinentry'
brew 'prettyping'
brew 'pth'
brew 'python', link: false
brew 'qemu'
brew 'qrencode'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'rust'
brew 'shfmt'
brew 'siege'
brew 'spark'
brew 'starship'
brew 'stow'
brew 'svn'
brew 'terminal-notifier'
brew 'thefuck'
brew 'tidy-html5'
brew 'tinygo'
brew 'tldr'
brew 'tmux'
brew 'trash'
brew 'tree'
brew 'vim'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'zsh-completions'

# Fonts
cask 'font-anonymous-pro'
cask 'font-fira-code'
cask 'font-hack'
cask 'font-hack-nerd-font'
cask 'font-ibm-plex'
cask 'font-inconsolata'
cask 'font-jetbrains-mono-nerd-font'
cask 'font-karla'
cask 'font-meslo-lg'
cask 'font-montserrat'
cask 'font-open-sans'
cask 'font-oswald'
cask 'font-pt-mono'
cask 'font-roboto'
cask 'font-roboto-mono'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-work-sans'

# Applications
cask 'alacritty'
cask 'appcleaner'
cask 'cryptomator'
cask 'brave-browser'
cask 'docker'
cask 'figma'
cask 'firefox'
cask 'fork'
cask 'google-chrome'
cask 'grammarly'
cask 'imageoptim'
cask 'osxfuse'
cask 'postico'
cask 'runjs'
cask 'signal'
cask 'webstorm'
cask 'zoom'

mas '1Blocker', id: 1365531024
mas '1Password for Safari', id: 568903335
mas 'Craft', id: 1487937127
mas 'Lungo', id: 1263070803
mas 'NextDNS', id: 1464122853
mas 'Slack', id: 803453959
mas 'Vinegar', id: 1591303229
mas 'Xcode', id: 497799835
mas 'xScope', id: 889428659
mas 'Vimari', id: 1480933944
