
# tap repositories and their packages

tap caskroom/cask
cask jet
cask qtpass
cask firefox
cask grammarly

tap caskroom/fonts
cask font-droid-sans-mono-for-powerline
cask font-anonymous-pro
cask font-inconsolata-for-powerline
cask font-playfair-display
cask font-inconsolata
cask font-roboto
cask font-pt-mono
cask font-work-sans
cask font-input
cask font-meslo-lg
cask font-ubuntu
cask font-liberation-mono-for-powerline
cask font-nixie-one
cask font-open-sans
cask font-office-code-pro
cask font-source-code-pro-for-powerline
cask font-dejavu-sans-mono-for-powerline
cask font-source-code-pro
cask font-oswald
cask font-droid-sans
cask font-fira-code
cask font-source-sans-pro
cask font-montserrat
cask font-liberation-sans
cask font-droid-sans-mono

tap homebrew/bundle

tap homebrew/core
brew pth
brew jpeg
brew gdbm
brew ripgrep
brew gpg-agent
brew gmp
brew pixman
brew freetype
brew libusb-compat
brew python
brew libvterm
brew libtermkey
brew gnutls
brew npth
brew p11-kit
brew libyaml
brew mercurial
brew unrar
brew cscope
brew pkg-config
brew tree
brew pass
brew jemalloc
brew ctop
brew msgpack
brew libunistring
brew libgpg-error
brew automake
brew exercism
brew libpng
brew boost
brew pcre
brew imagemagick
brew git-flow
brew libgcrypt
brew dirmngr
brew qrencode
brew ack
brew openssl
brew yarn
brew icu4c
brew awscli
brew adns
brew libtiff
brew tmux
brew vim
brew xz
brew fswatch
brew wget
brew qemu
brew neovim
brew libssh2
brew git
brew perl
brew emacs
brew gnu-getopt
brew glib
brew hub
brew ncurses
brew the_silver_searcher
brew libusb
brew libevent
brew ruby
brew libtasn1
brew cask
brew n
brew reattach-to-user-namespace
brew gnupg
brew autoconf
brew zsh
brew rust
brew sqlite
brew libassuan
brew cmake
brew hugo
brew gettext
brew coreutils
brew trash
brew node
brew mas
brew mongodb
brew pinentry
brew unibilium
brew libtool
brew openssl@1.1
brew libffi
brew readline
brew flow
brew bitrise
brew nettle
brew libksba
brew libuv

tap neovim/neovim

tap rcmdnk/file
brew brew-file
