theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
bufferline = "multiple"
auto-format = true
rulers = [80, 120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
  "workspace-diagnostics",
  "diagnostics",
  "selections",
  "position",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.search]
wrap-around = false

[keys.normal]
C-p = "file_picker"

[keys.normal."space"]
f = "file_picker_in_current_directory"
F = "file_picker"
